import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { CartProvider } from "./context/CartContext";
import { ProductsProvider } from "./context/ProductsContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next JS Boilerplate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <ProductsProvider>
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="flex-grow mt-20">{children}</main>
            <Footer />
          </div>
        </ProductsProvider>
      </body>
    </html>
  );
}
